version: '3'

services:
  docker-mysql:
    restart: always
    container_name: mysql-standalone
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    image: springio/docker
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
     WAIT_HOSTS: mysql:3306
    depends_on:
      - user-mysql